### PR TITLE
RFC/v2

### LINKED ISSUE #41: Example custom listener coupled to global WP function
## The Problem
The [custom listener example][] includes a `MyFilesListener` class. This class is coupled to the global WordPress function [`current_filter()`][]. This is not good for several obvious reasons. Alas, it does not seem possible to avoid this, because [`ActionListenerInterface#update()`][] does not provide any context which could be used to determine which hook is being handled.

## Suggested Solution
[`HookListenersRegistry#listen_hook()`][], the method which appears to [invoke the hook callback][1], looks like it receives the hook name as the first `$hook` parameter. If this value could be passed to [`HookListenersRegistry#hook_callback()`][], and then subsequently [passed to the `#update()` method][2], this would give listeners enough context to distinguish between hooks without relying on global context.

This would not break BC, because it would add a parameter to a method. Listener implementations that currently do not support this will simply get an extra argument, which will not be handled.

[custom listener example]: https://github.com/inpsyde/Wonolog/blob/master/docs/06-custom-hook-listeners.md#custom-listener-example
[`current_filter()`]: https://codex.wordpress.org/Function_Reference/current_filter
[`ActionListenerInterface#update()`]: https://github.com/inpsyde/Wonolog/blob/master/src/HookListener/ActionListenerInterface.php#L26
[`HookListenersRegistry#listen_hook()`]: https://github.com/inpsyde/Wonolog/blob/01605cd9e5a471df4cf9b8ed5260fd1355e8da11/src/HookListener/HookListenersRegistry.php#L98
[`HookListenersRegistry#hook_callback()`]: https://github.com/inpsyde/Wonolog/blob/01605cd9e5a471df4cf9b8ed5260fd1355e8da11/src/HookListener/HookListenersRegistry.php#L131
[1]: https://github.com/inpsyde/Wonolog/blob/01605cd9e5a471df4cf9b8ed5260fd1355e8da11/src/HookListener/HookListenersRegistry.php#L106
[2]: https://github.com/inpsyde/Wonolog/blob/01605cd9e5a471df4cf9b8ed5260fd1355e8da11/src/HookListener/HookListenersRegistry.php#L138

### LINKED ISSUE #48: Upgrade to Monolog 2*
Have you scheduled to upgrade Wonolog to be compatible with latest Monolog version (2.0 at least) ?
Thanks =)

### LINKED ISSUE #52: [2.x] Q&A improvments
We need to do following for version 2.x of Wonolog:

- Add Github Actions
- Add PSALM
- Add Inpsyde Coding Standards 1.x

All tests should pass, which also contains renaming methods and adding return types.

Minimum PHP version will be 7.2 because Monolog requires this as version.

### PR DESCRIPTION
**Pull request by gmazzap**
# RFC for v2

## Intro

I've been working on a few features and improvements that I'd like to see in Wonolog v2.

This includes anything mentioned in #52, #41, and #48, plus additional things that I'm going to list and describe here.

1. Improve / simplify bootstrap phase
2. Improve / simplify configuration of default handler
3. Code refactoring for general improvements and simplification
4. Refactoring of subscribe/update logic so that it can be easily re-used
5. Improvement on the "hook listener" logic
7. Introduce the possibility to register "log hook alias" 
8. Introduce the possibility to register "ignored pattern" to skip log events based on message pattern
9. Add a PSR-3 "façade" to be used for libraries that consume PSR-3 interfaces   
10. Introduce integration tests and improve existing unit tests

*(**Update 2020-12-31** There was a point about accepting generic PSR-logger via custom factories. That point has been removed because it introduced unnecessary complexity, and there's a more "native" way to deal with custom PSR-3 loggers which is now documented).*

### 1. Improve / simplify bootstrap phase

Currently configure Wonolog in its bootstrap phase is quite complicated.

The reason is that is is possible to use environment variables, constants, filter hooks, methods on the `Controller` class, flags to the bootstrap functions. 

This RFC introduces instead is a single `Configurator` class that via a fluent interface allows to configure all the aspects of Wonolog: one singe "entry-point" and one single way to do things.

There's also **no need to call `bootstrap()` function anymore**: the package, in fact, "bootstraps itself" firing an action that passes an instance of the `Configurator` which can be used to, well, configure Wonolog.

As example, here's a pretty advanced configuration that could be done:

```php
add_action(
    'wonolog.setup',
    static function (\Inpsyde\Wonolog\Configurator $config): void {
        $config
            ->withIgnorePattern('404 Page not found')
            ->disableFallbackHandlerForChannels(Channels::SECURITY)
            ->useTimezone(new \DateTimeZone('Europe/Rome'))
            ->pushHandlerForChannels($emailHandler, 'email', Channels::SECURITY)
            ->disableDefaultHookListeners(QueryErrorsListener::class)
            ->addActionListener('my-listener', $listener)
            ->registerLogHook('my-plugin.log', 'MY_PLUGIN')
            ->registerLogHook('another-plugin.log', 'ANOTHER_PLUGIN')
            ->pushProcessor('my-processor', static function (array $record): array {
                empty($record['extra']) and $record['extra'] = [];
                $record['extra']['project'] = getenv('PROJECT_NAME');
                return $record;
            });
    }
);
    
```

It is possible to see things like `withIgnorePattern()` and `registerLogHook()` that are new features introduced in this RFC and that will be detailed below.

Now that there's no need to call `bootstrap`, configuration can happen in different packages/mu-plugins where each package can do its part of configuration. 

### 2. Improve / simplify configuration of default handler

The Wonolog default handler is currently quite complicated to setup. The [factory class](https://github.com/inpsyde/Wonolog/blob/master/src/Handler/DefaultHandlerFactory.php) that instantiates it has five different filter hooks, plus it takes into account WordPress constants like `WP_CONTENT_DIR` and custom env var like `WONOLOG_DEFAULT_HANDLER_ROOT_DIR`.

On top of that, it could be totally replaced in at least three different ways.

This RFC introduces a simpler way to obtain configuration (if needed). That is, to provide the hander itself with a few configuration methods having a fluent interface.

First of all, the concept of *"default handler"*, as a handler *always* instantiated and assigned (unless specifically disabled) does not exist anymore. Now there's the concept of *"fallback handler"*: a handler that is instantiated and assigned only to channels having no other handlers (and can still be disabled entirely of for specific channels).

That means that users might ignore entirely the fallback handler shipped by Wonolog, and could push a completely custom handler. And in the case they still want to use the handler shipped with Wonolog (which has the benefit to play well in WordPress) they can configure that handler via a fluent interface.

An example, just to provide an idea:

```php
add_action('wonolog.setup', function (\Inpsyde\Wonolog\Configurator $config) {
    
    $handler = \Inpsyde\Wonolog\WonologFileHandler::new()
        ->withFolder('/logs/my-project')
        ->withDateBasedFileFormat('Ymd')
        ->withMinimumLevel(Logger::INFO)
        ->disableBubbling()
        ->pushProcessor($myProcessor);
    
    $config->pushHandler($handler);
});
```

*(**Update 202-12-31** the handler class is now renamed from `DefaultHandler` to  `WonologFileHandler`, because well, it is not a default handler anymore).*

### 3. Code refactoring for general improvements and simplification

Wonolog 1 still supports PHP 5.6. Moving to PHP 7.2+ there were a lot of things that could be improved and this RFC leverages that.

On top of that, the folder structure of the package was unnecessarily complex, so I though that a less complicated structure could make the codebase more easily understandable.

Finally, with the introduction of Psalm a lot of potential issues were found and fixed.

*(**Update 202-12-31** After feedback from @dnaber-de two additional root folders where added).*

### 4. Refactoring of subscribe/update logic so that it can be easily re-used

Wonolog 1 has a single class `LogActionSubscriber` that have *both* the responsibilities of *subscribing* to the "log hook" (`Inpsyde\Wonolog::LOG`) by being added as hook callback to it, and also to "*update*" the subscriber by actually performing the log.

This RFC splits these two responsibilities in two different classes. This means that the "update logic" can be reused and could be triggered by "things" that are not WordPress hooks, for example PSR-14 events or such.

### 5. Improvement on the "hook listener" logic

Considering that Wonolog 2 is going to have a backward compatibility break in hook listeners (due to the changes in #54) I wanted to take the change of seeing if there's something I could further improve there.

What I first realized is that hook listeners worked in Wonolog 1 by firing the Wonolog hook, so the workflow was:

1. listeners listen to arbitrary hooks
2. when hook are fired and listeners executed, listeners fire a `wonolog.log` action
3. the "main" Wonolog listener, react to  `wonolog.log` and perform the log

What I thought is that now that the "updater" logic is made independent would be possible to pass to hook listener the instance of the Wonolog "updater" so that at point *2.* listeners could directly trigger the log instead of firing an action that will make the log happen, saving one step and so improving performance.

This change also allowed to have a more consistent approach for "action" and "filter" listeners, with the only difference being that action listeners return nothing whereas filter listeners return the value to be returned to filter hook, with symmetry of what happen for action and filter hook callbacks.

### 6. Introduce the possibility to register custom "logging hooks" 

The simplest way for plugins/themes to perform logs via Wonolog is to do the `wonolog.log` action:

```php
do_action('wonolog.log', 'Something happened', $context);
```

Even this does not require any coupling with Wonolog (plugin/theme doesn't need to dependend on Wonolog) it still looks somehow coupled using the word "wonolog" in the hook. 

Moreover, if for a specific plugin/theme we want to use a plugin/theme specific channel it needs to be always passed explicitly.

```php
do_action(
  'wonolog.log',
  [
    'channel' => 'MY_PLUGIN',
    'message' => 'Something happened',
    'context' => $context
  ]
);
```

This RFC introduces the method `Configurator::registerLogHook()` that allow to define an alias for `wonolog.log` and at same time a default channel to be used for it.

For example:

```php
/** @var Inpsyde\Wonolog\Configurator $config */
$config->registerLogHook('myplugin.log', 'MY_PLUGIN');
```

The above code is *all* it is needed to be able to use things like:

```php
do_action('myplugin.log', 'Something happened', $context);
```

or even:

```php
do_action('myplugin.log.error', 'An error happened', $context);
```

And Wonolog will handle the log correctly using `MY_PLUGIN` as default channel, that it is still possible to override passing it explicitly.

*(**Update 202-12-31** The method was renamed from `registerLogHookAlias` to `registerLogHook` because for consumers it is not clear what the hook is "aliasing").*

### 8. Introduce the possibility to register "ignored pattern" to skip log events based on message pattern

It always happen that there's that particular error that happen again and again, which is not really possible to fix and for this reason floods the logs.

This RFC introduces the possibility to ignore such logs by using a regular expression pattern that applies on log message.

For example:

```php
/** @var Inpsyde\Wonolog\Configurator $config */
$config->withIgnorePattern('Undefined variable \$[^\s]+');
```

To avoid that high severity logs are missed due to ignored pattern, the method supports a "level threshold" to be used for each ignored pattern: any log record with that level or higher will not be ignored, by-passing the ignore pattern. For example:

```php
/** @var Inpsyde\Wonolog\Configurator $config */

// 500 is the Monolog equivalent for PSR-3 "CRITICAL" level
// if the message matching the matter will have that severity or higher
// will *not* be ignored.
$config->withIgnorePattern('Undefined variable \$[^\s]+', 500);
```

Finally, ignore patterns can be limited to one or more channels, passing a variadic number of channel names from the third argument:

```php
/** @var Inpsyde\Wonolog\Configurator $config */
$config->withIgnorePattern('Undefined variable \$[^\s]+', 500, 'MY_PLUGIN', 'DEBUG');
```

### 9. Introduce PSR-3 "façade"

When using "generic" PHP libraries that require a PSR-3 implementation it was not straightforward to provide a single PSR-3 logger that would "forward" logs to Wonolog.

This RFC introduces a PSR-3 `LoggerInterface` "façade" that can be passed to object that consume PSR-3. The way to obtain such façade it is needed to call `Inpsyde\Wonolog\makeLogger()` function.

For example:

```php
$someLogAwareObject = new Something();
$someLogAwareObject ->setLogger(Inpsyde\Wonolog\makeLogger());
```

Because PSR-3 has _no_ concept of "logs channel", it is possible to set a default channel for all the logs that will be processed by the logger. That is done passing the channel name to the `makeLogger` function:

```php
$someLogAwareObject = new Something();
$someLogAwareObject ->setLogger(Inpsyde\Wonolog\makeLogger("some-channel"));
```

This parameter is optional, if not provided the default Wonolog channel will be used.

Note that the channel can still be set per-log by passing it in the `"channel"` property of the [log's "context" array](https://www.php-fig.org/psr/psr-3/#13-context).

It's worth noting that `makeLogger` will return a working logger after (or at least during) [`"muplugins_loaded"` action hook](https://developer.wordpress.org/reference/hooks/muplugins_loaded/). That means it is always fine to call in plugins and themes.
MU plugins and any Composer-based package that executes before `"muplugins-loaded"` need to make sure to call it with proper timing.
However, even if called earlier `makeLogger` will return a [`Psr\Log\NullLogger`](https://github.com/php-fig/log/blob/master/Psr/Log/NullLogger.php) to don't break any type declaration.

### 10. Introduce integration tests and improve existing unit tests

This RFC introduces a few tests that run loading WordPress, Monolog, and Wonolog, simulating a real world environment to make sure that all the pieces play well together.

These tests are designed to run in Docker and the RFC includes all the Docker configuration files.

On top of that, existing tests are adapted to the new code/folder structure, and/or to all the introduced changes, new unit tests for introduced classes are added. All unit tests in this RFC generically make a less "generous" use of mocking, preferring usage of real package classes when convenient / possible.

## New documentation

The documentation as been reworked entirely:

- It describes new features and changes
- It's less Monolog-centric, (Monolog is mentioned very few times)

It can be found here: https://github.com/inpsyde/Wonolog/tree/rfc/v2/docs

*(**Update 202-12-31** The documentation should now be complete).*

## Why a single RFC pull request

When I started working to introduce the changes i wanted to have, the original idea was to have separate issues each with a related PR, but I quickly realized that each of the change I wanted impacted large part of the codebase, and so the only way to obtain what I wanted had been to create a series of "chained" PRs, with one based on the code of the other.

That is something extremely hard to manage for several reasons: if one PR is changed, the PR that depends on it needs to change, and that might be an issue if those are approved already, because reviewers would need to review again. Moreover, GitHub has no tool to manage dependencies across issues and PRs.

So I decided to create a single PR that I call a RFC because it presents a lot of changes that I would like to be reviewed at the same time in the code and in the concept and then (informally) voted and in case they are accepted we can merge them for v2.

It must be clear tough that there's **no reason at all this PR / RFC has to be merged all at once**.

Changes can be approved and rejected separately, and based on the decision taken I will take care of updating this PR or maybe, if that's easier, close this and create other.

## How to proceed

I think that this PR is just too big to be reviewed on-line. I would so expect reviewers to first all understand the concepts express here and evaluate them, and then checkout the RFC branch locally and review there in the comfort of own IDE.

After that I would expect them to provide a feedback that would include things like "*I like this change as is*" / "*I don't like this change and do not want to see it in Wonolog 2.0*" / "*I like the change idea but before merging in Wonolog 2 I would like to add/remove/change X, Y, and Z*".

Of course, generic suggestions / improvements / comments on the code are very welcomed.

### CODE REVIEW

**Comment by Chrico** [comment]
I really like that idea and changes! Some of those concepts are even solving current problems (like the "ignore" pattern).

A few things which are comming into my mind:

------
## Ignore Pattern

Should we also allow to "bind" the ignore pattern to a specific Channel(s)? Something like: 

```php
Wonolog::withIgnorePattern(string $pattern, array $channels = [])
```

----

## Naming

I guess the naming is still not "final", but maybe we should consider some more specific names like:

- `Wonolog::disableDefaultHookListeners($className)` -> `Wonolog::disableHookListeners($className)`

----

## Processors, Handlers, Logger(s) and Channels, PSR-3 and more

a) A `Handler` can be registered to a Channel via `Wonolog::pushHandlerForChannels($handler, $name, $channel)`, 
b) but a `Processor` can only be pushed to all via `Wonolog::pushProcessor($myProcessor);`.

PSR-3 does not define any Handler/Processor concept, but our Wonolog package is build on top of Monolog - which has Handler/Processors bound to the Logger. For me it was always kind of irritating, that Wonolog needs a Handler and not a (multiple) Logger to run.

----

more will come at a later point....maybe it's easier to have a call and write down some conclusion then starting here a bigger discussion about... the concept itself. :)

**Comment by gmazzap** [comment]
@Chrico

> Should we also allow to "bind" the ignore pattern to a specific Channel(s)? Something like:

That's already possible.

[`Configurator::withIgnorePattern` method](https://github.com/inpsyde/Wonolog/blob/rfc/v2/src/Configurator.php#L335-L339) has the following signature:

```php
public function withIgnorePattern(
    string $ignorePattern,
    ?int $levelThreshold = null,
    string ...$channels
): Configurator
```

You can pass a variadic number of channels at the end of the funciton and limit the ignore patterns to those channels.

---

> but maybe we should consider some more specific names like:

Consider that `toggleDefaultHookListeners::disableDefaultHookListeners()` only allows to disable one or more _default_ hook listeners, that are defined in [`Configurator::DEFAULT_HOOK_LISTENERS` constant](https://github.com/inpsyde/Wonolog/blob/rfc/v2/src/Configurator.php#L47-L55). If we name it `disableHookListeners` the name becomes misleading.

---

> PSR-3 does not define any Handler/Processor concept

This PR allows you to push even a generic PSR-3 LoggerInterface, don't need to be a Monolog logger or handler.

To do this you define a callback that receives a string with channel name and returns a PSR-3 logger.

For example, you could do:

```php
\Inpsyde\Wonolog\bootstrap()->withLoggerFactory(function (string $channel) {
   return new MyPsr3Logger();
});
```

With this 3 lines of code you can use a custom PSR-3 logger that is not even a Monolog handler.
Because the callback receives the channel name, you could use some logic specific for channels.

But if you already know that there are specific channels that you want to use the custom PSR-3 logger, you can do:

```php
\Inpsyde\Wonolog\bootstrap()->withLoggerFactoryForChannels(function (string $channel) {
   return new MyPsr3Logger();
}, 'CHANNEL_ONE', 'CHANNEL_2');
```

In this case the custom PSR-3 logger will be used for those 2 channels. Because those are custom channels, the functions already register them, without requiring to register them separately.

Note that this workflow is not limited to PSR-3 `LoggerInterface`, but can also be used to factory a Monolog `Logger`. 

---

> For me it was always kind of irritating, that Wonolog needs a Handler and not a (multiple) Logger to run.

Wonolog works with multiple loggers. Each logger is a channel: 1 channel <=> 1 logger.

However, you can see a Logger as a collection of handlers. So instead of "pushing a logger" you can push an array of handlers to all/some channels, and Wonolog will take care of "wrapping" those handlers, making them available to the logger that belongs to the channel(s) you are targeting.

Regarding processors, Monolog works with 2 kind of processors:
- processors for handlers
- processessor for loggers

Handlers can have processors only if they implement interface `ProcessableHandlerInterface` (introduced in Monolog 2), loggers can have processors if they are (or extend) Monolog `Logger` class.

If you push a collection of handlers, it means that you can take care of adding processors to the handlers you pass. Regarding processors, Wonolog allows you to add processors for specific channels, and because 1 channel = 1 logger, you can have control on the logger's processors.

Imagine that you want to add a logger `MyLogger` to the channel `my-plugin`.

If Wonolog would allow you to add loggers, you would do:

```php
$handerOne = new HandlerOne();
$handerOne->pushProcessor(new SomeProcessor());
$logger = new Logger();
$logger->pushHandler($handerOne);
$logger->pushHandler(new HandlerTwo());
$logger->pushProcessor(new AnotherProcessor());

bootstrap()->addLogger($logger, "my-plugin"); // this does not exist
```

with the current code you do:

```php
$handerOne = new HandlerOne();
$handerOne->pushProcessor(new SomeProcessor());

bootstrap()
  ->pushHandlerForChannels($handerOne, HandlerOne::class, "my-plugin")
  ->pushHandlerForChannels(new HandlerTwo(), HandlerTwo::class, "my-plugin")
  ->pushProcessorForChannels(AnotherProcessor::class, new AnotherProcessor(), "my-plugin");
```

The two code snippets do exact same thing: add, for the single `my-plugin` channel, a logger with:
- 2 handlers (one of those with a processor)
- a processor

The second snippet (that is how the code is now) is slightly less (6 lines instead of 7), but that's not the reason why things are the way they are.

The reason is that if _another_ MU plugin (or package) wants to reuse the handlers and/or the processors used in the second snippet, that's very possible because handlers and processors are located in `HandlersRegistry` and `ProcessorsRegistry` so it is possible to easily reuse them.

If Wonolog would accept ready-made loggers (like in first snippet) it would not be possible to reuse loggers and or processors. For example, if there's a `EmailHandler` that I want to add to my logger, I will need to instantiate the same handler again and again, once per logger, and that's specially annoying because usually handlers needs configuration.

A generic processor, like [`WpContextProcessor`](https://github.com/inpsyde/Wonolog/blob/rfc/v2/src/WpContextProcessor.php) that adds WP-specific information to logs, would also need to be instantiated again and again for each logger to add.

That is the reason why Wonolog accepts _handlers_ and _processors_ and not ready-made loggers.

That said, with the new `withLoggerFactory` you can still override that, the only differencee is that instead of adding a logger, you add a callback that returns a logger.

For example, even if the `addLogger` method doesn't exist, you can still do (with pretty much same code):

```php
bootstrap()->withLoggerFactoryForChannels(function (string $channel) {
    $handerOne = new HandlerOne();
    $handerOne->pushProcessor(new SomeProcessor());
    $logger = new Logger();
    $logger->pushHandler($handerOne);
    $logger->pushHandler(new HandlerTwo());
    $logger->pushProcessor(new AnotherProcessor());

    return $logger;
}, 'my-plugin');
```

The reason to accept a factory callback instead of an object is that by using a factory is still possible to _inject_ processors that other packages might add.

For example, if a package has the code above, _another_ package can do:

```php
bootstrap()
  ->enableWpContextProcessor()
  ->pushProcessor(AnotherProcessor::class, new AnotherProcessor());
```

and the 2 processors (the defaut `WpContextProcessor` and the custom `AnotherProcessor`) will be added to the custom logger created by the callback, but only if it implements `ProcessableHandlerInterface`. Because the logger is created lazily (via a factory callback) even if the package that adds processor is executed before the package that adds the logger factory, it is still possible to add processors to logger added later.

That means from the factory  you're free to return a simple PSR-3 logger, but in case you decide to implement `ProcessableHandlerInterface`, (e.g. using a full Monolog `Logger`) it becomes extendable by reusable processors.

Unfortunately the handlers are not reusable... and if another package want's to reuse the same handlers will need to instantiate them again, and if those handlers needs configuration that will be copied and pasted... This is why, unless really necessary, I think it is still better to push handlers and loggers and not ready-made loggers.

**Comment by dnaber-de** [comment]
Giuseppe, thanks for moving things forward and for this detailed elaboration of the updates.

I like the idea of the fluent interfaces to build configuration that makes things a lot easier. Anyway I am a bit concerned about the concept of ignoring log records by a message pattern even though I clearly understand the intention. Recently I found myself in a similar situation outside of WordPress context that for example HTTP 4xx exceptions or deprecation notices create a lot of noise in the logs which you want clearly remove.

It is in the nature of these records that they tend to make the vast majority of all records which leads to the concern that applying a regular expression on each and every log record might result in a notable performance impact especially on sites that has a lot of traffic and or using plugins that produces a lot of notices. A maybe a bit less impacting method would be a simple string comparison with `strpos()`?

My second concern is that especially HTTP 4xx exceptions might not be thrown away completely. An alternative would be that these ignored records could be sent to a dedicated channel which can be handled separately if wanted.

Last thing, what do you think about managing some of the classes in the `src/` directory in one or two additional domains like `Factory` and `Processor`, IMO the readability would benefit from it.

**Comment by gmazzap** [comment]
Thanks @dnaber-de 

> It is in the nature of these records that they tend to make the vast majority of all records which leads to the concern that applying a regular expression on each and every log record might result in a notable performance

Regex have a bad reputation, but relatively easy patterns do not perform that bad on modern versions of PHP. Consider that in case of multiple strings, thanks to regex `|` operator, comparison can be done calling `preg_match` once, but with `strpos` you would need to call multiple times.

Far from being scientically precise, I did an attempt to compare 5000 executions of `preg_match` with the equivalent `strpos` and I got this:
-  `preg_match`: https://3v4l.org/8HlvS
- `stripos`: https://3v4l.org/iFnJ9 

As you can see results are entirely comparable, and sometimes the `preg_match` version is even faster.

---

> My second concern is that especially HTTP 4xx exceptions might not be thrown away completely. An alternative would be that these ignored records could be sent to a dedicated channel which can be handled separately if wanted.

Those exceptions are collected by the `HttpApiListener` which you could decorate and make it use a different channel:

```php
add_action(
    'wonolog.setup',
    static function (Configurator $config) {
        $config
            ->disableDefaultHookListeners(HttpApiListener::class)
            ->addActionListener(new Ignored404Listener(new HttpApiListener()));
    }
);
``` 

This would be much easier if some methods of `HttpApiListener` would be protected instead of private, and I'm fine to do it if we agree.

---

> Last thing, what do you think about managing some of the classes in the src/ directory in one or two additional domains like Factory and Processor, IMO the readability would benefit from it.

Lately I'm a fan of a folder structure as flat as possible, and I like to use folders when there are _a few_ classes that would go in a folder (my non-strict rule of thumb is >= 3).

The possible folders I see are:

- a `/Registry` folder could contain: `HandlersRegistry`, `HookListenersRegistry`, and `ProcessorsRegistry`
- a `/Processor` folder, could contain: `NullProcessor`, and `WpContextProcessor`
- a `/Factory` folder could contain `Factory`, and `HookLogFactory`

My >= 3 rule of thumb would say only  "Registry" folder qualify, but I would be fine in introducing the other two folders, especially if others agree.

**Comment by gmazzap** [comment]
@Chrico I deleted my previous answer to you because was too long and this is not a right place for long comments. 

Will try to answer point-by-point in a short way.

> Should we also allow to "bind" the ignore pattern to a specific Channel(s)?

That is possible already. I updated the text of the RFC to include that, and in any case it is documented.

---

> Should we also allow to "bind" the ignore pattern to a specific Channel(s)?

`disableDefaultHookListeners` is a method that disabled _default_ hook listeners, not all default listeners, that's the reason for naming. The documentation explain it well (I hope). Basically, in v2, all plugins/themes/packages are encouraged to either
- option 1: make use of logging hooks and register the log hook in Wonolog
- option 2: rely on PSR-3 logger and then make it possible to inject Wonolog PSR-3 logger

For code that we can't change, we need to use hook listeners. And because WordPress is not under our control, Wonolog ships hook listeners for WordPress, and those are called "default hook listeners".

---

> Processors, Handlers, Logger(s) and Channels, PSR-3 and more

In Wonolog v2 the dependency to Monolog is almost "hidden", in fact, the new documentation barely mention it.
The concept of "Logger" is an internal concept in Wonolog v2. The documentation never mention "Logger".
Wonolog has "channels", each channel is a "category" for logs. Each channels can be assigned to one or more handlers and one or more processors.
Regarding PSR-3, consider that Wonolog is something that _provides_ PSR-3 implemetation, not necessarily _accepts_ it. In rare cases in which you're provided with a ready-amde PSR-3 logger, e.g. coming from you hosting, you can still add a [`PsrHandler`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/PsrHandler.php).
All this is documented.

---

Generally speaking, I think the new approach of Wonolog 2 is well explained in the documentation: https://github.com/inpsyde/Wonolog/tree/rfc/v2/docs.

When you've time please take some minutes to read it, it probably will answer better than it is possible to answer here to all questions you had, and also to all questions you did not write :)

**Pull request merged**
